# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from soupsieve import select
from Relabel import MyLabel
from ReRadio import MyRadio


class Ui_MainWindow(object):

    select_1 = 0
    select_2 = 0
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1118, 862)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.picture_1 = MyLabel(self.centralwidget)
        self.picture_1.setGeometry(QtCore.QRect(400, 40, 200, 200))
        self.picture_1.setFrameShape(QtWidgets.QFrame.Box)
        self.picture_1.setObjectName("picture_1")
        

        self.picture_6 = MyLabel(self.centralwidget)
        self.picture_6.setGeometry(QtCore.QRect(910, 280, 200, 200))
        self.picture_6.setFrameShape(QtWidgets.QFrame.Box)
        self.picture_6.setObjectName("picture_6")

        self.picture_2 = MyLabel(self.centralwidget)
        self.picture_2.setGeometry(QtCore.QRect(650, 40, 200, 200))
        self.picture_2.setFrameShape(QtWidgets.QFrame.Box)
        self.picture_2.setObjectName("picture_2")

        self.picture_9 = MyLabel(self.centralwidget)
        self.picture_9.setGeometry(QtCore.QRect(910, 540, 200, 200))
        self.picture_9.setFrameShape(QtWidgets.QFrame.Box)
        self.picture_9.setObjectName("picture_9")

        self.picture_4 = MyLabel(self.centralwidget)
        self.picture_4.setGeometry(QtCore.QRect(400, 290, 200, 200))
        self.picture_4.setFrameShape(QtWidgets.QFrame.Box)
        self.picture_4.setObjectName("picture_4")

        self.picture_7 = MyLabel(self.centralwidget)
        self.picture_7.setGeometry(QtCore.QRect(400, 540, 200, 200))
        self.picture_7.setFrameShape(QtWidgets.QFrame.Box)
        self.picture_7.setObjectName("picture_7")

        self.picture_5 = MyLabel(self.centralwidget)
        self.picture_5.setGeometry(QtCore.QRect(650, 280, 200, 200))
        self.picture_5.setFrameShape(QtWidgets.QFrame.Box)
        self.picture_5.setObjectName("picture_5")

        self.picture_3 = MyLabel(self.centralwidget)
        self.picture_3.setGeometry(QtCore.QRect(910, 40, 200, 200))
        self.picture_3.setFrameShape(QtWidgets.QFrame.Box)
        self.picture_3.setObjectName("picture_3")

        self.picture_8 = MyLabel(self.centralwidget)
        self.picture_8.setGeometry(QtCore.QRect(650, 540, 200, 200))
        self.picture_8.setFrameShape(QtWidgets.QFrame.Box)
        self.picture_8.setObjectName("picture_8")


        
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 210, 151, 581))
        self.groupBox.setObjectName("groupBox")

        self.rButton_hairorange = MyRadio(self.groupBox,self)
        self.rButton_hairorange.setGeometry(QtCore.QRect(30, 310, 115, 19))
        self.rButton_hairorange.setObjectName("rButton_hairorange")
        self.rButton_hairblack = MyRadio(self.groupBox,self)
        self.rButton_hairblack.setGeometry(QtCore.QRect(30, 70, 115, 19))
        self.rButton_hairblack.setObjectName("rButton_hairblack")
        self.rButton_hairbrown = MyRadio(self.groupBox,self)
        self.rButton_hairbrown.setGeometry(QtCore.QRect(30, 190, 115, 19))
        self.rButton_hairbrown.setObjectName("rButton_hairbrown")
        self.rButton_hairblue = MyRadio(self.groupBox,self)
        self.rButton_hairblue.setGeometry(QtCore.QRect(30, 150, 115, 19))
        self.rButton_hairblue.setObjectName("rButton_hairblue")
        self.rButton_hairpurple = MyRadio(self.groupBox,self)
        self.rButton_hairpurple.setGeometry(QtCore.QRect(30, 390, 115, 19))
        self.rButton_hairpurple.setObjectName("rButton_hairpurple")
        self.rButton_hairaqua = MyRadio(self.groupBox,self)
        self.rButton_hairaqua.setGeometry(QtCore.QRect(30, 30, 115, 19))
        self.rButton_hairaqua.setObjectName("rButton_hairaqua")
        self.rButton_hairgreen = MyRadio(self.groupBox,self)
        self.rButton_hairgreen.setGeometry(QtCore.QRect(30, 270, 115, 19))
        self.rButton_hairgreen.setObjectName("rButton_hairgreen")
        self.rButton_hairgrey = MyRadio(self.groupBox,self)
        self.rButton_hairgrey.setGeometry(QtCore.QRect(30, 230, 115, 19))
        self.rButton_hairgrey.setObjectName("rButton_hairgrey")
        self.rButton_hairblonde = MyRadio(self.groupBox,self)
        self.rButton_hairblonde.setGeometry(QtCore.QRect(30, 110, 115, 19))
        self.rButton_hairblonde.setObjectName("rButton_hairblonde")
        self.rButton_hairpink = MyRadio(self.groupBox,self)
        self.rButton_hairpink.setGeometry(QtCore.QRect(30, 350, 115, 19))
        self.rButton_hairpink.setObjectName("rButton_hairpink")
        self.rButton_hairred = MyRadio(self.groupBox,self)
        self.rButton_hairred.setGeometry(QtCore.QRect(30, 430, 115, 19))
        self.rButton_hairred.setObjectName("rButton_hairred")
        self.rButton_hairwhite = MyRadio(self.groupBox,self)
        self.rButton_hairwhite.setGeometry(QtCore.QRect(30, 470, 115, 19))
        self.rButton_hairwhite.setObjectName("rButton_hairwhite")

       
        self.to_another = QtWidgets.QPushButton(self.centralwidget)
        self.to_another.setGeometry(QtCore.QRect(90, 40, 211, 101))
        self.to_another.setObjectName("to_another")


        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 210, 151, 581))
        self.groupBox_2.setObjectName("groupBox_2")
        self.rButton_eyepurple = MyRadio(self.groupBox_2,self)
        self.rButton_eyepurple.setGeometry(QtCore.QRect(30, 310, 115, 19))
        self.rButton_eyepurple.setObjectName("rButton_eyepurple")
        self.rButton_eyeblack = MyRadio(self.groupBox_2,self)
        self.rButton_eyeblack.setGeometry(QtCore.QRect(30, 70, 115, 19))
        self.rButton_eyeblack.setObjectName("rButton_eyeblack")
        self.rButton_eyegreen = MyRadio(self.groupBox_2,self)
        self.rButton_eyegreen.setGeometry(QtCore.QRect(30, 190, 115, 19))
        self.rButton_eyegreen.setObjectName("rButton_eyegreen")
        self.rButton_eyebrown = MyRadio(self.groupBox_2,self)
        self.rButton_eyebrown.setGeometry(QtCore.QRect(30, 150, 115, 19))
        self.rButton_eyebrown.setObjectName("rButton_eyebrown")
        self.rButton_eyeyellow = MyRadio(self.groupBox_2,self)
        self.rButton_eyeyellow.setGeometry(QtCore.QRect(30, 390, 115, 19))
        self.rButton_eyeyellow.setObjectName("rButton_eyeyellow")
        self.rButton_eyeaqua = MyRadio(self.groupBox_2,self)
        self.rButton_eyeaqua.setGeometry(QtCore.QRect(30, 30, 115, 19))
        self.rButton_eyeaqua.setObjectName("rButton_eyeaqua")
        self.rButton_eyepink = MyRadio(self.groupBox_2,self)
        self.rButton_eyepink.setGeometry(QtCore.QRect(30, 270, 115, 19))
        self.rButton_eyepink.setObjectName("rButton_eyepink")
        self.rButton_eyeorange = MyRadio(self.groupBox_2,self)
        self.rButton_eyeorange.setGeometry(QtCore.QRect(30, 230, 115, 19))
        self.rButton_eyeorange.setObjectName("rButton_eyeorange")
        self.rButton_eyeblue = MyRadio(self.groupBox_2,self)
        self.rButton_eyeblue.setGeometry(QtCore.QRect(30, 110, 115, 19))
        self.rButton_eyeblue.setObjectName("rButton_eyeblue")
        self.rButton_eyered = MyRadio(self.groupBox_2,self)
        self.rButton_eyered.setGeometry(QtCore.QRect(30, 350, 115, 19))
        self.rButton_eyered.setObjectName("rButton_eyered")

    
        # 生成BTN
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 170, 93, 28))
        self.pushButton.setObjectName("pushButton")
        
        self.pushButton.clicked.connect(self.generation)


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.picture_3.setText(_translate("MainWindow", "图片三"))
        self.picture_8.setText(_translate("MainWindow", "图片八"))
        self.groupBox.setTitle(_translate("MainWindow", "头发颜色"))
        self.rButton_hairorange.setText(_translate("MainWindow", "橘黄色"))
        self.rButton_hairblack.setText(_translate("MainWindow", "黑色"))
        self.rButton_hairbrown.setText(_translate("MainWindow", "棕黄色"))
        self.rButton_hairblue.setText(_translate("MainWindow", "蓝色"))
        self.rButton_hairpurple.setText(_translate("MainWindow", "紫色"))
        self.rButton_hairaqua.setText(_translate("MainWindow", "浅绿色"))
        self.rButton_hairgreen.setText(_translate("MainWindow", "绿色"))
        self.rButton_hairgrey.setText(_translate("MainWindow", "灰色"))
        self.rButton_hairblonde.setText(_translate("MainWindow", "金黄色"))
        self.rButton_hairpink.setText(_translate("MainWindow", "粉色"))
        self.rButton_hairred.setText(_translate("MainWindow", "红色"))
        self.rButton_hairwhite.setText(_translate("MainWindow", "白色"))
        self.picture_7.setText(_translate("MainWindow", "图片七"))
        self.picture_5.setText(_translate("MainWindow", "图片五"))
        self.to_another.setText(_translate("MainWindow", "风格迁移->"))
        self.groupBox_2.setTitle(_translate("MainWindow", "眼睛颜色"))
        self.rButton_eyepurple.setText(_translate("MainWindow", "紫色"))
        self.rButton_eyeblack.setText(_translate("MainWindow", "黑色"))
        self.rButton_eyegreen.setText(_translate("MainWindow", "绿色"))
        self.rButton_eyebrown.setText(_translate("MainWindow", "棕黄色"))
        self.rButton_eyeyellow.setText(_translate("MainWindow", "黄色"))
        self.rButton_eyeaqua.setText(_translate("MainWindow", "浅绿色"))
        self.rButton_eyepink.setText(_translate("MainWindow", "粉色"))
        self.rButton_eyeorange.setText(_translate("MainWindow", "橘黄色"))
        self.rButton_eyeblue.setText(_translate("MainWindow", "蓝色"))
        self.rButton_eyered.setText(_translate("MainWindow", "红色"))
        self.picture_9.setText(_translate("MainWindow", "图片九"))
        self.picture_4.setText(_translate("MainWindow", "图片四"))
        self.picture_1.setText(_translate("MainWindow", "图片一"))
        self.picture_2.setText(_translate("MainWindow", "图片二"))
        self.pushButton.setText(_translate("MainWindow", "生成"))
        self.picture_6.setText(_translate("MainWindow", "图片六"))

    def generation(self):
        print("申奥成功了")   
        print("select_1"+self.select_1)
        print("select_2"+self.select_2)

